services:
  postgres:
    image: postgres:15-alpine
    container_name: auction_postgres
    environment:
      POSTGRES_DB: auction_db
      POSTGRES_USER: auction_user
      POSTGRES_PASSWORD: auction_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U auction_user -d auction_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  bot:
    build: .
    container_name: auction_bot
    environment:
      TG_BOT_TOKEN: ${TG_BOT_TOKEN}
      CREATOR_ID: ${CREATOR_ID:-1337}
      DATABASE_URL: postgresql://auction_user:auction_password@postgres:5432/auction_db
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:

